//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserInfoEntitiesCon : DbContext
    {
        public UserInfoEntitiesCon()
            : base("name=UserInfoEntitiesCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactTable> ContactTables { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
